name: Deploy ModuleX

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_PATH: ~/modulex

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      working-directory: ./py
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    
    - name: Run tests
      working-directory: ./py
      run: |
        python -m pytest tests/ || echo "No tests found, skipping..."

  deploy:
    name: Deploy to Azure VM
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Deploy to Production
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        timeout: 600s
        command_timeout: 300s
        script: |
          set -e  # Exit on any error
          
          echo "🚀 Starting ModuleX deployment..."
          echo "📅 Deployment time: $(date)"
          
          # Project directory
          PROJECT_DIR="/home/${{ secrets.USERNAME }}/modulex"
          
          # Check if directory exists
          if [ ! -d "$PROJECT_DIR" ]; then
            echo "❌ Project directory not found: $PROJECT_DIR"
            exit 1
          fi
          
          cd "$PROJECT_DIR"
          
          # Backup current state
          echo "💾 Creating backup..."
          BACKUP_DIR="~/backups/modulex-$(date +%Y%m%d_%H%M%S)"
          mkdir -p ~/backups
          cp -r . "$BACKUP_DIR" || echo "⚠️ Backup failed, continuing..."
          
          # Git operations
          echo "📥 Fetching latest changes"
          git fetch origin
          
          # Check if there are changes
          LOCAL=$(git rev-parse HEAD)
          REMOTE=$(git rev-parse origin/main)
          
          if [ "$LOCAL" = "$REMOTE" ]; then
            echo "✅ Already up to date!"
            exit 0
          fi
          
          echo "🔄 Updating from $LOCAL to $REMOTE"
          git reset --hard origin/main
          
          # Pre-deployment checks
          echo "🔍 Pre-deployment checks..."
          
          # Check if docker-compose.yml exists
          if [ ! -f "docker-compose.yml" ]; then
            echo "❌ docker-compose.yml not found!"
            exit 1
          fi
          
          rm -f /home/${{ secrets.USERNAME }}/modulex/docker/env/modulex.env
          echo '${{ secrets.MODULEX_ENV }}' > /home/${{ secrets.USERNAME }}/modulex/docker/env/modulex.env
          
          # Check if .env exists, create from example if not
          if [ ! -f "docker/env/modulex.env" ]; then
            echo "⚠️ .env not found, copying from env.example..."
            cp docker/env/modulex.env.example docker/env/modulex.env
          fi
          
          # Stop services gracefully
          echo "🛑 Stopping services..."
          docker-compose down --timeout 30

          df -h
          free -m
          sudo systemctl restart docker
          
          # Clean up old images (optional)
          echo "🧹 Cleaning up old images..."
          docker image prune -f || echo "⚠️ Image cleanup failed"
          
          # Build new images
          echo "🔨 Building new images..."
          docker-compose build --no-cache --parallel
          
          # Start services
          echo "▶️ Starting services..."
          docker-compose up -d
          
          # Simple wait
          echo "⏳ Waiting for services to stabilize..."
          sleep 60
          
          # Show final status
          echo "📊 Deployment Summary:"
          echo "=========================="
          docker-compose ps
          echo ""
          echo "🎉 Deployment completed!"

  notify:
    name: Notify Deployment Status
    runs-on: ubuntu-latest
    needs: [deploy]
    if: always()
    
    steps:
    - name: Notify Success
      if: needs.deploy.result == 'success'
      run: |
        echo "✅ ModuleX deployed successfully!"
        # Buraya Slack/Discord notification ekleyebilirsiniz
    
    - name: Notify Failure
      if: needs.deploy.result == 'failure'
      run: |
        echo "❌ ModuleX deployment failed!"
        # Buraya failure notification ekleyebilirsiniz